# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.183.0/containers/javascript-node/.devcontainer/base.Dockerfile

# [Choice] Node.js version: 16, 14, 12
ARG VARIANT="16-buster"
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT}

# [Optional] Uncomment this section to install additional OS packages.
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
        git \
    && mkdir -p /workspaces \
    && chown node /workspaces \
    && su node -c "cd /workspaces && git clone https://github.com/MichMich/MagicMirror" \
    && su node -c "cd /workspaces/MagicMirror && npm install" \
    && su node -c "cd /workspaces/MagicMirror && cp config/config.js.sample config/config.js" \
    && su node -c "cd /workspaces/MagicMirror && npm install pm2 -g"
